#!/usr/bin/python

import sys
import Image

from ibpy import pdf_gen, imb

class Config(object):
    def __init__(self):
        object.__init__(self)

def imb2pdf(in_fn, out_fn):
    ibook = imb.Book()
    ibook.load(in_fn)
    if len(ibook.pages) == 0:
        return
    img_fns = [ipage.img_fn for ipage in ibook.pages]
    img = Image.open(ibook.pages[0].img_fn)
    print dir(ibook)
    config = Config()
    config.title = ibook.title
    config.author = ibook.author
    config.bookmarks = ibook.toc_entries
    config.out_size = img.size
    config.rotate = 0
    config.out_file_name = out_fn

    pg = pdf_gen.PDFGenerator(config)
    pg.generate(img_fns)

def usage():
    print 'Usage: %s <input file>.imb <output file>.pdf' % (sys.argv[0],)
    sys.exit(-1)

if __name__ == '__main__':
    if len(sys.argv) != 3:
        usage()
    imb2pdf(sys.argv[1], sys.argv[2])
