#!/usr/bin/python
#
# Copyright 2008 Huang Ying <huang.ying.caritas@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

import sys
import ibpy

def reformat(args):
    ibpy.reformat(args)

if __name__ == '__main__':
    reformat(sys.argv)
